
spring.profiles.active: dev
feed.filename: demo.feed

---

spring:
    profiles: dev
debug: true

---

spring:
    profiles: prod
debug: false

---

audit.amount:
    deposit: 99
    withdrawal: 99

